### ISSUE TITLE
We need to auto-generate Docker images

### ISSUE THREAD

**Issue by egeland** [kube-aws/kube-spot-termination-notice-handler#3]
### Acceptance Criteria
* A `latest` image is generated from the `master` branch, on commit.
* A version-tagged image is generated when a tag is made to the git repo.
* The README is updated to indicate where the image repository is.

**Comment by egeland** [comment]
@mumoshu - did you say we can use Quay.io?

**Comment by mumoshu** [comment]
@egeland Yes. Would you mind sharing your quay username so that I can provide you necessary permissions on the repo?

**Comment by mumoshu** [comment]
Hi @egeland, I believe we can safely use the [kubeaws](https://hub.docker.com/u/kubeaws/) org. on DockerHub.

I had somehow misunderstood that someone took the more official'ish `kube-aws` on DockerHub(notice the missing hyphen between words), but it turned out that DockerHub doesn't allow hyphen inside user/org names.

What we have today - `kubeaws` - is the official'ish one and you already have write permissions to create repos/push images under the org.

**Comment by egeland** [comment]
I really should get onto this.. :sweat_smile:

**Comment by egeland** [comment]
I've finally set up the [DockerHub automatic build](https://hub.docker.com/r/kubeaws/kube-spot-termination-notice-handler/). Still need to update the readme..

**Comment by egeland** [comment]
I migrated the latest two images to the new repo.
